### ISSUE TITLE
Issue downloading videos off main feed..

### ISSUE THREAD

**Issue by jtabalujan** [Zipdox/tiktok-download-userscript#3]
As the title reads, if the video is on the main feed, the userscript downloads the video just fine. However, if for example it's taken directly from the user's profile feed, you get a 386 byte file.

I looked into more and it seems like the userscript is failing when trying to fetch or pull the blob info?

**Comment by Zipdox** [comment]
It's completely broken, I give up. Tiktok changes their shit too often.
